version: "{build}"

skip_tags: true

environment:
  matrix:
    - nodejs_version: 7
    - nodejs_version: 6

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm --version
  - npm run test
  - npm run build

build: off

cache:
  - node_modules -> package.json
